module ReviewConfig exposing (config)

{-| elm-review configuration for rivcomocktrial.

Rule packages:
  - jfmengels/elm-review-unused  — catch dead code and unused exports
  - jfmengels/elm-review-debug   — prevent Debug.log/todo from shipping

Custom rules:
  - NoPbOrApiInMigratedPages — architecture lock for the active
    domain refactor (ADR-012). Pages migrated to the new
    architecture cannot import `Api` or `Pb`. Per-page allowlist
    in the rule shrinks one entry per slice.

.elm-land/ is generated by elm-land; excluded from all rules.

Debug.todo is intentional in tests/ — used as "crash on invalid fixture"
helpers (e.g. crashOnError in TestHelpers). NoDebug rules only apply to src/.

To add more rules: `elm install <author>/<package>` inside frontend/review/,
then add the rule module here.

-}

import NoDebug.Log
import NoDebug.TodoOrToString
import NoPbOrApiInMigratedPages
import NoUnused.CustomTypeConstructors
import NoUnused.Dependencies
import NoUnused.Exports
import NoUnused.Modules
import NoUnused.Parameters
import NoUnused.Patterns
import NoUnused.Variables
import Review.Rule exposing (Rule)


config : List Rule
config =
    [ NoDebug.Log.rule
        |> Review.Rule.ignoreErrorsForDirectories [ ".elm-land/", "tests/" ]
    , NoDebug.TodoOrToString.rule
        |> Review.Rule.ignoreErrorsForDirectories [ ".elm-land/", "tests/" ]
    , NoUnused.Variables.rule
        |> Review.Rule.ignoreErrorsForDirectories [ ".elm-land/" ]
    , NoUnused.Parameters.rule
        |> Review.Rule.ignoreErrorsForDirectories [ ".elm-land/" ]
    , NoUnused.Patterns.rule
        |> Review.Rule.ignoreErrorsForDirectories [ ".elm-land/" ]
    , NoUnused.Dependencies.rule
        |> Review.Rule.ignoreErrorsForDirectories [ ".elm-land/" ]
    , NoUnused.Modules.rule
        |> Review.Rule.ignoreErrorsForDirectories [ ".elm-land/" ]
    , NoUnused.CustomTypeConstructors.rule []
        |> Review.Rule.ignoreErrorsForDirectories [ ".elm-land/" ]
    , NoUnused.Exports.rule
        |> Review.Rule.ignoreErrorsForDirectories [ ".elm-land/" ]
    , NoPbOrApiInMigratedPages.rule
    ]
