/// <reference path="../pb_data/types.d.ts" />
// Seed RCOE admin superusers. Idempotent — skips emails that already
// exist. The first email is flagged as primary_contact so it shows up
// as the public RCOE contact on registration pages.
//
// Each new superuser gets a random 32-char password they never need.
// They sign in via password reset / magic link in production.
//
// To add or change admins, edit ADMINS below and create a follow-up
// migration. Do not edit this file once it has run.
migrate(
  (app) => {
    const ADMINS = [
      { email: "mknust@rcoe.us", isPrimaryContact: true },
      { email: "jlucky@jamsadr.com", isPrimaryContact: false },
      { email: "YCHAVELAS@rcoe.us", isPrimaryContact: false },
      { email: "ajuarez@rcoe.us", isPrimaryContact: false },
      { email: "MGMoore@RivCoDA.org", isPrimaryContact: false },
    ];

    const collection = app.findCollectionByNameOrId("_superusers");

    for (const admin of ADMINS) {
      try {
        const existing = app.findFirstRecordByFilter(
          "_superusers",
          "email = {:email}",
          { email: admin.email }
        );
        if (existing) {
          // Already exists — make sure the primary-contact flag is right
          // but don't touch anything else.
          if (Boolean(existing.get("is_primary_contact")) !== admin.isPrimaryContact) {
            existing.set("is_primary_contact", admin.isPrimaryContact);
            app.save(existing);
          }
          continue;
        }
      } catch (_) {
        // findFirstRecordByFilter throws when no match — that's the create path.
      }

      const password = $security.randomString(32);
      const record = new Record(collection);
      record.set("email", admin.email);
      record.set("password", password);
      record.set("is_primary_contact", admin.isPrimaryContact);
      app.save(record);
    }
  },
  (app) => {
    // No-op down. Reference data is too dangerous to auto-delete.
  }
);
