#!/bin/sh
# Print every credential the project needs as KEY=VALUE lines, pulled from
# 1Password. This is the ONLY place we shell out to `op` — everything else
# reads env vars from .env.local (loaded automatically by direnv).
#
# Usage:
#   scripts/load-1p-creds.sh > .env.local
#
# Re-run any time you rotate a credential in 1Password. Until then,
# .env.local stays in place and direnv keeps it loaded for every shell.
#
# Requires: 1Password CLI (op) authenticated.

set -e

if ! command -v op >/dev/null 2>&1; then
    echo "1Password CLI (op) not found on PATH" >&2
    exit 1
fi

# Sanity check that op is actually signed in. `op whoami` exits non-zero
# if the session has expired.
if ! op whoami >/dev/null 2>&1; then
    echo "1Password CLI is not signed in. Run \`op signin\` first." >&2
    exit 1
fi

read_field() {
    item="$1"
    field="$2"
    val=$(op read "${item}/${field}" 2>/dev/null || true)
    if [ -z "$val" ]; then
        echo "Could not read ${item}/${field} from 1Password." >&2
        exit 1
    fi
    printf '%s' "$val"
}

DEV_EMAIL=$(read_field "op://Private/localhost-dev-admin-user" "username")
DEV_PASSWORD=$(read_field "op://Private/localhost-dev-admin-user" "password")

STAGING_ADMIN_EMAIL=$(read_field "op://Private/rivcomocktrial-staging-admin" "username")
STAGING_ADMIN_PASSWORD=$(read_field "op://Private/rivcomocktrial-staging-admin" "password")
STAGING_COACH_EMAIL=$(read_field "op://Private/rivcomocktrial-staging-user" "username")
STAGING_COACH_PASSWORD=$(read_field "op://Private/rivcomocktrial-staging-user" "password")

PROD_ADMIN_EMAIL=$(read_field "op://Private/rivcomocktrial" "username")
PROD_ADMIN_PASSWORD=$(read_field "op://Private/rivcomocktrial" "password")

cat <<EOF
# Generated by scripts/load-1p-creds.sh — gitignored.
# Re-run after rotating any credential in 1Password.

PB_DEV_ADMIN_EMAIL=${DEV_EMAIL}
PB_DEV_ADMIN_PASSWORD=${DEV_PASSWORD}

STAGING_BASE_URL=https://rivcomocktrial-staging.fly.dev
STAGING_ADMIN_EMAIL=${STAGING_ADMIN_EMAIL}
STAGING_ADMIN_PASSWORD=${STAGING_ADMIN_PASSWORD}
STAGING_COACH_EMAIL=${STAGING_COACH_EMAIL}
STAGING_COACH_PASSWORD=${STAGING_COACH_PASSWORD}

PROD_BASE_URL=https://rivcomocktrial.org
PROD_ADMIN_EMAIL=${PROD_ADMIN_EMAIL}
PROD_ADMIN_PASSWORD=${PROD_ADMIN_PASSWORD}
EOF
