name: Deploy to fly.io

on:
  push:
    branches: [main]
    paths:
      - "web/**"
      - "backend/**"
      - "fly.staging.toml"
      - "fly.toml"
      - ".dockerignore"
  workflow_dispatch:
    inputs:
      target:
        description: Target environment
        required: true
        type: choice
        options:
          - staging
          - production
        default: staging

jobs:
  staging:
    if: github.event_name == 'push' || github.event.inputs.target == 'staging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  production:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'production'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
